package sitterwasm

import (
	"context"
	"embed"
	"fmt"
	"strings"
)

// Built-in grammar artifacts are generated from the C runtime and grammar by
// the mise/Docker workflow. Keeping them embedded makes the package
// immediately usable without a compiler or cgo on the target machine.
//
//go:embed internal/wasm/assets/*.wasm
var builtinAssets embed.FS

// BuiltinWASM returns a copy of an embedded grammar module by its language
// name. It returns nil when the language has not been checked into this
// package. Language names are intentionally restricted to simple artifact
// names so a caller cannot escape the embedded asset directory.
func BuiltinWASM(language string) []byte {
	return builtinWASMBytes(language)
}

func normalizeBuiltinLanguage(language string) string {
	return strings.ToLower(strings.TrimSpace(language))
}

// validBuiltinLanguage reports whether a name can safely identify an embedded
// artifact. Keeping this check separate makes constructors use the same
// normalized value that BuiltinWASM uses for its lookup.
func validBuiltinLanguage(language string) bool {
	if language == "" || strings.ContainsAny(language, "/\\") {
		return false
	}
	for _, r := range language {
		if (r < 'a' || r > 'z') && (r < '0' || r > '9') && r != '_' && r != '-' {
			return false
		}
	}
	return true
}

// builtinWASMName normalizes and validates a language name before it is used
// as an embedded filesystem path.
func builtinWASMName(language string) string {
	language = normalizeBuiltinLanguage(language)
	if !validBuiltinLanguage(language) {
		return ""
	}
	return language
}

// builtinWASMBytes performs the actual embedded lookup. It is kept private so
// public helpers can consistently report unavailable artifacts.
func builtinWASMBytes(language string) []byte {
	language = builtinWASMName(language)
	if language == "" {
		return nil
	}
	b, err := builtinAssets.ReadFile("internal/wasm/assets/sitterwasm-" + language + ".wasm")
	if err != nil {
		return nil
	}
	return append([]byte(nil), b...)
}

// BuiltinJSONWASM returns a copy of the embedded JSON Tree-sitter module.
func BuiltinJSONWASM() []byte { return BuiltinWASM("json") }

// BuiltinJavaScriptWASM returns a copy of the embedded JavaScript Tree-sitter
// module. The artifact is generated by `mise run build:grammar javascript`.
func BuiltinJavaScriptWASM() []byte { return BuiltinWASM("javascript") }

// NewBuiltinRuntime creates a Runtime from an embedded grammar artifact.
func NewBuiltinRuntime(ctx context.Context, language string) (*Runtime, error) {
	name := builtinWASMName(language)
	wasm := builtinWASMBytes(name)
	if len(wasm) == 0 {
		return nil, fmt.Errorf("sitterwasm: embedded grammar %q is unavailable: %w", language, ErrUnsupported)
	}
	r, err := NewRuntime(ctx, wasm)
	if err != nil {
		return nil, err
	}
	grammar, err := r.LoadLanguage(name)
	if err != nil {
		_ = r.Close()
		return nil, err
	}
	_ = grammar.Close()
	return r, nil
}

// NewJSONRuntime creates a Runtime containing the built-in JSON grammar.
func NewJSONRuntime(ctx context.Context) (*Runtime, error) {
	return NewBuiltinRuntime(ctx, "json")
}

// NewJavaScriptRuntime creates a Runtime containing the embedded JavaScript
// grammar.
func NewJavaScriptRuntime(ctx context.Context) (*Runtime, error) {
	return NewBuiltinRuntime(ctx, "javascript")
}

// NewJSONParser is a convenience constructor that returns a parser already
// configured with the built-in JSON grammar.
func NewJSONParser(ctx context.Context) (*Parser, *Runtime, error) {
	return NewBuiltinParser(ctx, "json")
}

// NewBuiltinParser creates a parser configured with an embedded grammar
// artifact. The corresponding Runtime is returned to let callers control its
// lifetime; close the parser before closing the runtime.
func NewBuiltinParser(ctx context.Context, language string) (*Parser, *Runtime, error) {
	name := builtinWASMName(language)
	r, err := NewBuiltinRuntime(ctx, name)
	if err != nil {
		return nil, nil, err
	}
	grammar, err := r.LoadLanguage(name)
	if err != nil {
		_ = r.Close()
		return nil, nil, err
	}
	p, err := NewParserWithRuntime(r)
	if err != nil {
		_ = grammar.Close()
		_ = r.Close()
		return nil, nil, err
	}
	if err := p.SetLanguage(grammar); err != nil {
		_ = grammar.Close()
		_ = p.Close()
		_ = r.Close()
		return nil, nil, err
	}
	_ = grammar.Close()
	return p, r, nil
}

// NewJavaScriptParser creates a parser configured with the embedded
// JavaScript grammar.
func NewJavaScriptParser(ctx context.Context) (*Parser, *Runtime, error) {
	return NewBuiltinParser(ctx, "javascript")
}
